import os


SCRIPT_CLASS_MAP = {
    "Script": ".server.luau",
    "LocalScript": ".client.luau",
    "ModuleScript": ".luau",
}


def emit_script(base_dir, path_stack, name, class_name, source):
    ext = SCRIPT_CLASS_MAP[class_name]

    folder = os.path.join(base_dir, *path_stack)
    os.makedirs(folder, exist_ok=True)

    file_path = os.path.join(folder, name + ext)

    with open(file_path, "w", encoding="utf-8") as f:
        f.write("-- ⚠️ Auto-generated by rbxlx-rojo-converter\n")
        f.write("-- Review this script manually\n\n")
        f.write(source)

    return file_path
